export interface KemendikdasmenSubjectOption {
  value: string;
  label: string;
  level: "sd-sma" | "smk";
}

export const KEMENDIKDASMEN_SUBJECTS: KemendikdasmenSubjectOption[] = [
  { value: "pendidikan-agama-islam-dan-budi-pekerti", label: "Pendidikan Agama Islam dan Budi Pekerti", level: "sd-sma" },
  { value: "pendidikan-agama-kristen-dan-budi-pekerti", label: "Pendidikan Agama Kristen dan Budi Pekerti", level: "sd-sma" },
  { value: "pendidikan-agama-katolik-dan-budi-pekerti", label: "Pendidikan Agama Katolik dan Budi Pekerti", level: "sd-sma" },
  { value: "pendidikan-agama-buddha-dan-budi-pekerti", label: "Pendidikan Agama Buddha dan Budi Pekerti", level: "sd-sma" },
  { value: "pendidikan-agama-hindu-dan-budi-pekerti", label: "Pendidikan Agama Hindu dan Budi Pekerti", level: "sd-sma" },
  { value: "pendidikan-agama-khonghucu-dan-budi-pekerti", label: "Pendidikan Agama Khonghucu dan Budi Pekerti", level: "sd-sma" },
  { value: "pendidikan-pancasila", label: "Pendidikan Pancasila", level: "sd-sma" },
  { value: "bahasa-indonesia", label: "Bahasa Indonesia", level: "sd-sma" },
  { value: "matematika", label: "Matematika", level: "sd-sma" },
  { value: "ilmu-pengetahuan-alam-dan-sosial-ipas", label: "Ilmu Pengetahuan Alam dan Sosial (IPAS)", level: "sd-sma" },
  { value: "ilmu-pengetahuan-alam", label: "Ilmu Pengetahuan Alam", level: "sd-sma" },
  { value: "ilmu-pengetahuan-sosial", label: "Ilmu Pengetahuan Sosial", level: "sd-sma" },
  { value: "bahasa-inggris", label: "Bahasa Inggris", level: "sd-sma" },
  { value: "pendidikan-jasmani-olahraga-dan-kesehatan-pjok", label: "Pendidikan Jasmani, Olahraga, dan Kesehatan (PJOK)", level: "sd-sma" },
  { value: "informatika", label: "Informatika", level: "sd-sma" },
  { value: "seni-musik", label: "Seni Musik", level: "sd-sma" },
  { value: "seni-rupa", label: "Seni Rupa", level: "sd-sma" },
  { value: "seni-tari", label: "Seni Tari", level: "sd-sma" },
  { value: "seni-teater", label: "Seni Teater", level: "sd-sma" },
  { value: "prakarya", label: "Prakarya", level: "sd-sma" },
  { value: "sejarah", label: "Sejarah", level: "sd-sma" },
  { value: "sejarah-tingkat-lanjut", label: "Sejarah Tingkat Lanjut", level: "sd-sma" },
  { value: "geografi", label: "Geografi", level: "sd-sma" },
  { value: "geografi-tingkat-lanjut", label: "Geografi Tingkat Lanjut", level: "sd-sma" },
  { value: "ekonomi", label: "Ekonomi", level: "sd-sma" },
  { value: "ekonomi-tingkat-lanjut", label: "Ekonomi Tingkat Lanjut", level: "sd-sma" },
  { value: "sosiologi", label: "Sosiologi", level: "sd-sma" },
  { value: "sosiologi-tingkat-lanjut", label: "Sosiologi Tingkat Lanjut", level: "sd-sma" },
  { value: "antropologi", label: "Antropologi", level: "sd-sma" },
  { value: "fisika", label: "Fisika", level: "sd-sma" },
  { value: "fisika-tingkat-lanjut", label: "Fisika Tingkat Lanjut", level: "sd-sma" },
  { value: "kimia", label: "Kimia", level: "sd-sma" },
  { value: "kimia-tingkat-lanjut", label: "Kimia Tingkat Lanjut", level: "sd-sma" },
  { value: "biologi", label: "Biologi", level: "sd-sma" },
  { value: "biologi-tingkat-lanjut", label: "Biologi Tingkat Lanjut", level: "sd-sma" },
  { value: "matematika-tingkat-lanjut", label: "Matematika Tingkat Lanjut", level: "sd-sma" },
  { value: "bahasa-inggris-tingkat-lanjut", label: "Bahasa Inggris Tingkat Lanjut", level: "sd-sma" },
  { value: "bahasa-arab", label: "Bahasa Arab", level: "sd-sma" },
  { value: "bahasa-jepang", label: "Bahasa Jepang", level: "sd-sma" },
  { value: "bahasa-jerman", label: "Bahasa Jerman", level: "sd-sma" },
  { value: "bahasa-korea", label: "Bahasa Korea", level: "sd-sma" },
  { value: "bahasa-mandarin", label: "Bahasa Mandarin", level: "sd-sma" },
  { value: "bahasa-prancis", label: "Bahasa Prancis", level: "sd-sma" },
  { value: "dasar-dasar-akuntansi-dan-keuangan-lembaga", label: "Dasar-dasar Akuntansi dan Keuangan Lembaga", level: "smk" },
  { value: "dasar-dasar-broadcasting-dan-perfilman", label: "Dasar-dasar Broadcasting dan Perfilman", level: "smk" },
  { value: "dasar-dasar-desain-komunikasi-visual", label: "Dasar-dasar Desain Komunikasi Visual", level: "smk" },
  { value: "dasar-dasar-kuliner", label: "Dasar-dasar Kuliner", level: "smk" },
  { value: "dasar-dasar-manajemen-perkantoran-dan-layanan-bisnis", label: "Dasar-dasar Manajemen Perkantoran dan Layanan Bisnis", level: "smk" },
  { value: "dasar-dasar-pemasaran", label: "Dasar-dasar Pemasaran", level: "smk" },
  { value: "dasar-dasar-pengembangan-perangkat-lunak-dan-gim", label: "Dasar-dasar Pengembangan Perangkat Lunak dan Gim", level: "smk" },
  { value: "dasar-dasar-teknik-jaringan-komputer-dan-telekomunikasi", label: "Dasar-dasar Teknik Jaringan Komputer dan Telekomunikasi", level: "smk" },
  { value: "dasar-dasar-teknik-ketenagalistrikan", label: "Dasar-dasar Teknik Ketenagalistrikan", level: "smk" },
  { value: "dasar-dasar-teknik-mesin", label: "Dasar-dasar Teknik Mesin", level: "smk" },
  { value: "dasar-dasar-teknik-otomotif", label: "Dasar-dasar Teknik Otomotif", level: "smk" },
  { value: "dasar-dasar-teknologi-farmasi", label: "Dasar-dasar Teknologi Farmasi", level: "smk" },
  { value: "dasar-dasar-usaha-layanan-pariwisata", label: "Dasar-dasar Usaha Layanan Pariwisata", level: "smk" },
  { value: "rekayasa-perangkat-lunak", label: "Rekayasa Perangkat Lunak", level: "smk" },
  { value: "teknik-komputer-dan-jaringan", label: "Teknik Komputer dan Jaringan", level: "smk" },
  { value: "teknik-kendaraan-ringan", label: "Teknik Kendaraan Ringan", level: "smk" },
];

export function subjectLabelForSlug(slug: string) {
  return KEMENDIKDASMEN_SUBJECTS.find((subject) => subject.value === slug)?.label || "";
}
